### ISSUE TITLE
printf(" %p %p ", 0, 0); em linux retorna (null) e em MAC retorna 0x0 .

### ISSUE THREAD

**Issue by lipemecprec** [paulo-santana/ftprintf-tester#2]
Olá meu querido, tudo bem?

Me parece que a saída do teste 9 do %p está travada em 0x0, que é a saída do MAC, mas agora teremos um IDE que avalia em linux também. Assim, se for possível, poderia incluir um check de OS para isso?

algo como:
```# if __APPLE__
#  define IS_MACOS 1
# else
#  define IS_MACOS 0
# endif```
na sua lib.

**Comment by paulo-santana** [comment]
Eae mano,

O jeito que o projeto está atualmente já está fazendo isso, checando se o OS é linux pra printar igual o Mac. Então pra mudar isso eu vou ter que apagar essa checagem kk

**Comment by lipemecprec** [comment]
Rapaz! Que estranho... bom, mas dá hora que achou ai como resolver!
Valeu!!
