### ISSUE TITLE
 Unexplained tester behaviour on Darwin.

### ISSUE THREAD

**Issue by stankudrow** [paulo-santana/ftprintf-tester#5]
I am testing my project (https://github.com/stankudrow/ft_printf) on Ubuntu (20.04) and tests go fine. However, the tester spawns multiple KO's when checking on MacOS (Mojave) at School. Nevertheless, trying tests cases "manually" with a simple main shows no discrepancy in neither total bytes processed nor the printed output.

**Comment by paulo-santana** [comment]
Sorry for the late response. The tests were built with just linux on mind. If you're being evaluated on Macs, consider adapting these tests to have the behavior of your operating system.
